#!/bin/sh

# This is where postgresql connection parameters are read from
TESTENV=../config/environments/test.js

# NOTE: assumes existance of a "template_postgis" loaded with
#       compatible version of postgis (legacy.sql included)


# Extract postgres configuration
PGSQL_CONF=`cat ${TESTENV} | sed -n '1h;1!H;${g;s/.*postgres *= *{\([^}]*\)}.*/\1/;p}'`
#echo $PGSQL_CONF

PGUSER=`echo $PGSQL_CONF | sed "s/.*user: '\([^']*\)'.*/\1/"`
echo "PGUSER: [$PGUSER]"
PGHOST=`echo $PGSQL_CONF | sed "s/.*host: '\([^']*\)'.*/\1/"`
echo "PGHOST: [$PGHOST]"
PGPORT=`echo $PGSQL_CONF | sed "s/.*port: \([^,$]*\).*/\1/"`
echo "PGPORT: [$PGPORT]"

export PGUSER PGHOST PGPORT

die() {
        msg=$1
        echo "${msg}" >&2
        exit 1
}

echo "...Configuring Windshaft test database"

echo "...Recreating windshaft_test database"
dropdb windshaft_test | 2>&1
createdb -Ttemplate_postgis -EUTF8 windshaft_test || die "Could not create test database" 

echo "...Populating windshaft_test database with test data"
psql windshaft_test < ./fixtures/windshaft.test.sql

echo "...Test database configuration complete"
